[package]
name = "jetson-tensorflow-rust"
version = "0.1.0"
authors = ["Luis Nieves <nievesh.lf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = "0.14.0"